services:
  vdf-web:
    build:
      context: .
      dockerfile: VDF.Web/Dockerfile
    image: vdf-web:compare-optimized
    ports:
      - "7777:8080"
    environment:
      - VDF_WEB_PASSWORD=111
    volumes:
      - /volume7/Datastore1/Videos:/mnt/Videos
      - /volume5/docker/vdf/config:/root/.config/VDF
      - /volume5/docker/vdf/db:/root/.local/state/VDF
